apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: LoadBalancer
  selector:
    app: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    name: hzport

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hazelcast
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast-node
        image: {{ .Values.images.hazelcast.image }}
        ports:
        - containerPort: 5701
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration
