apiVersion: v1
kind: Service
metadata:
  name: mancenter
  labels:
    app: mancenter
spec:
  type: LoadBalancer
  selector:
    app: mancenter
  ports:
  - protocol: TCP
    port: 8080
    name: mancenter-port

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mancenter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mancenter
    spec:
      containers:
      - name: mancenter
        image: hazelcast/management-center
        ports:
        - containerPort: 8080
          protocol: TCP
